name: release xcframework
on: workflow_dispatch
jobs:
  release-xc:
    name: release-xcframework
    runs-on: macos-latest
    environment:
      name: production
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/cert_repo_ed25519
          chmod 600 ~/.ssh/cert_repo_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add ~/.ssh/cert_repo_ed25519
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2

      - name: setup bundle
        run: bundle install

      - name: setup mint
        run: brew install mint

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Calculate next version
        id: next_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          dry_run: true

      - name: setup assets
        run: |
          git submodule update --remote --init --recursive --force
          xcrun --sdk macosx swiftc -swift-version 5 -parse-as-library ./Scripts/Build.swift -o ./Scripts/Build
          ./Scripts/Build

      - name: run fastlane disable logs and create xcframework.zip
        run: bundle exec fastlane create_xc
        env:
          MATCH_KEYCHAIN_NAME: ${{secrets.MATCH_KEYCHAIN_NAME}}
          MATCH_KEYCHAIN_PASSWORD: ${{secrets.MATCH_KEYCHAIN_PASSWORD}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          APPLE_ID: ${{secrets.APPLE_ID}}
          CER_NAME: ${{secrets.CER_NAME}}
          CER_REPO: ${{secrets.CER_REPO}}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.MATCH_GIT_BASIC_AUTHORIZATION}}
          INCREMENTED_VERSION: ${{steps.next_version.outputs.new_tag}}
          FASTLANE_SKIP_ACTION_SUMMARY: true
          FASTLANE_HIDE_PLUGINS_TABLE: true

      - name: Bump_version
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_version.outputs.new_tag }}
          body: ${{ steps.next_version.outputs.changelog }}
          files: fastlane/export/release/PhosphorBinary.xcframework.zip

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Bump version to ${{ steps.next_version.outputs.new_tag }}

      - name: cleanup
        run: rm ~/.ssh
